name: gemgis_dev_env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  # geopandas will also install numpy, pandas, shapely, pyogrio, and pyproj
  - geopandas>=1.0.1
  - shapely>=2.0.6
  - pandas>=2.2.3
  - numpy>=2.1.3
  - affine>=2.4.0
  - pyproj>=3.7.0
  # rasterio will also install affine
  - rasterio>=1.4.3
  # pyvista also install pooch and matplotlib
  - pyvista>=0.44.2
  - matplotlib>=3.9.3
  - gemgis>=1.1
  - rioxarray
  - scipy
  - owslib
  - scikit-image
  - mplstereonet
  - pypdf
  - xmltodict
  - geopy
  - scikit-learn
  - tqdm
  - requests
  - pooch<1.5.0
  - pip
  - pip:
    - gempy>=2.3
    - PVGeo
    - pyqt5
    - nbsphinx
    - sphinx_markdown_tables
    - sphinx_gallery
    - sphinx_rtd_theme
    - sphinx_book_theme==0.3.3
    - sphinx_copybutton
    - sphinx_automodapi
    - sphinx_numfig
    - numpydoc
    - build
