name: gemgis_dev_env
channels:
  - conda-forge
dependencies:
  - python>=3.11
  # geopandas will also install numpy, pandas, shapely, pyogrio, and pyproj
  - geopandas>=1.1.1
  - shapely>=2.1.1
  - pandas>=2.3.2
  - numpy>=2.3.2
  - pyproj>=3.7.2
  # rasterio will also install affine
  - rasterio>=1.4.3
  - affine>=2.4.0
  # pyvista also install pooch and matplotlib
  - pyvista>=0.46.3
  - matplotlib>=3.10.6
  - gemgis>=1.1.8
  - rioxarray
  - scipy
  - owslib
  - scikit-image
  - mplstereonet
  - pypdf
  - xmltodict
  - geopy
  - scikit-learn
  - tqdm
  - requests
  - pooch<1.5.0
  - pip
  - pip:
    - gempy>=2025.2.0
    - PVGeo
    - pyqt5
    - nbsphinx
    - sphinx_markdown_tables
    - sphinx_gallery
    - sphinx_rtd_theme
    - sphinx_book_theme==0.3.3
    - sphinx_copybutton
    - sphinx_automodapi
    - sphinx_numfig
    - numpydoc
    - build
